### ISSUE TITLE
Question: Video integration???

### ISSUE THREAD

**Issue by HackShitUp** [pauljeannot/SnapSliderFilters#10]

**Comment by crossle** [comment]
Create a VideoComposition apply to AVAssetExportSession
http://stackoverflow.com/questions/39114863/applying-a-cifilter-to-a-video-file-and-saving-it

**Comment by pauljeannot** [comment]
Hi ! 
A video version is more complicated than this implementation, and would not been compatible with what have been done there. @crossle link is a good way to start with.

**Comment by HackShitUp** [comment]
Yea, I started using GPUImage, and stopped using this.
