### ISSUE TITLE
Add XIB/Storyboard support

### ISSUE THREAD

**Issue by QuentinArnault** [pauljeannot/SnapSliderFilters#13]
Will you be interested if I propose a pull request with support of XIB and storyboard?

**Comment by pauljeannot** [comment]
Hi @QuentinArnault !
I have been quite busy last months without chance to maintain this repo, sorry for being so late ! I guess your proposal is now out of date, but I am starting to write a brand new version updated to Swift 4 with a much easier way to use it, and I will try to add XIB/Storyboard integration.
If you are still motivated, feel free to ping me ! 👋
