### ISSUE TITLE
Original image rotates by -90 while sliding the filters

### ISSUE THREAD

**Issue by kidvicious** [pauljeannot/SnapSliderFilters#16]
I implemented the codes according to the instructions and everything works fine except that the filtered image rotates 
![27605039_2028215167193115_240298480_o](https://user-images.githubusercontent.com/33537978/35608889-38356fd2-0683-11e8-9897-8ebf95640550.jpg)
![27605492_2028215193859779_1587449819_o](https://user-images.githubusercontent.com/33537978/35608890-39a23134-0683-11e8-822f-21be0740357b.jpg)

**Comment by gdelarosa** [comment]
I'm getting the same issue.

**Comment by dannylnz** [comment]
Hi, Did you find a way to solve this? 
I am getting the image rotation and its also presented with a weird scale

**Comment by Sonali2009** [comment]
Resize the image using this - image.resizeWithWidth(SNUtils.screenSize.width) -> UIImage. Then assign the result image to self.image in init() function of SNFilter. You can also change the content mode as per your requirement. It worked for me.

**Comment by pauljeannot** [comment]
Hi, sorry for being late.
As mentionned by @Sonali2009, there is a way to avoid this weird scaling/rotation.
You can check out [this gist](https://gist.github.com/schickling/b5d86cb070130f80bb40), I think this can solve the issue.
A new version of this repo is coming with a built-in solution.
