### ISSUE TITLE
Is there a way to provide custom / additional filters?

### ISSUE THREAD

**Issue by jguffey** [pauljeannot/SnapSliderFilters#17]
The documentation suggests that there is a way to generate any type of filter "using the Core Image Filter.", but https://github.com/pauljeannot/SnapSliderFilters/blob/master/SnapSliderFilters/Classes/SNFilter.swift#L59 seems to filter out any filters that do not already appear in the list. 

Perhaps I'm just needing some hints or example implementation of a custom filter in order to see what I'm doing incorrectly.

Thanks for the awesome cocopod 👍 !

**Comment by pauljeannot** [comment]
Hi @jguffey ! 

You can use [built in filters provided by Apple](https://developer.apple.com/library/content/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html), or you can also create yours (but I have never tried it).

There is an interesting WWDC session about that : https://developer.apple.com/videos/play/wwdc2014/515/.
