### ISSUE TITLE
resignFirstResponder -hideKeyboard

### ISSUE THREAD

**Issue by alejandrorbradford** [pauljeannot/SnapSliderFilters#3]
I'm trying to hide the keyboard whenever I press a button. But it seems it is not calling the function within the class. any ideas?

**Comment by alejandrorbradford** [comment]
looks like its only resigning first responder only when I touch the keyboard's view

**Comment by pauljeannot** [comment]
Hi @alejandrorbradford, sorry for the delay !

To hide the keyboard with a button, you only have to write this line in its action method : 

``` swift
self.textField?.resignFirstResponder()
```

Paul
