### ISSUE TITLE
Update to swift 2.3 or 3.0

### ISSUE THREAD

**Issue by oldenburg1990** [pauljeannot/SnapSliderFilters#4]
Hi Paul

Just wanted to hear if you have any plans on updating this project to swift 2.3 or 3.0 in the near future so that it can be used in newer, up-to-date projects?

Best
Jonas

**Comment by pauljeannot** [comment]
Hi @oldenburg1990,

It will be done very soon, sorry for the delay!
Paul

**Comment by sebleon** [comment]
@pauljeannot any updates on this?

**Comment by pauljeannot** [comment]
@sebleon , @oldenburg1990 Hi guys, I had some trouble with the swift 3.0 migration, but **here it is** !
Paul
