### ISSUE TITLE
Using SNUtils.screenShot

### ISSUE THREAD

**Issue by ghost** [pauljeannot/SnapSliderFilters#5]
I am using SNUtils.screenShot to save the filters, but it automatically saves to my library on the phone. How can I disable this?

**Comment by pauljeannot** [comment]
Hi @xScylez,
That is very strange. The screenShot method should not save anything into your library. Are you sure that you are not calling `UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil)` at the same time ?

**Comment by ghost** [comment]
Hm, looks like I had to comment out that line in `Pods/SnapFliderFilters/SNUtils.swift`

```
public class SNUtils {

    public static let screenSize = CGSize(width: UIScreen.mainScreen().bounds.width, height: UIScreen.mainScreen().bounds.height)

    public static func screenShot(view: UIView) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(view.frame.size, true, 0.0)
        view.drawViewHierarchyInRect(view.bounds, afterScreenUpdates: true)
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        //UIImageWriteToSavedPhotosAlbum(image!, nil, nil, nil)
        return image!
    }
}
```

**Comment by pauljeannot** [comment]
Of course that was the problem. Be careful, it looks like you are not dealing with the last version of this repo, that's perhaps why you have had this weird line in there!
