### ISSUE TITLE
installing the framework

### ISSUE THREAD

**Issue by HarishHary** [pauljeannot/SnapSliderFilters#7]
hi, 

I have an issue on installing your framework. Seem like, even if a install your framework. I can't find it. And Xcode find 30 more issues. Which is super weird. I am installing the version 1.0.1. And i don't know if it's the latest version.

This was the message given by cocoapod.

> Analyzing dependencies
Downloading dependencies
Installing SnapSliderFilters (1.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

This is my podfile.  
> target 'WindChat' do
 use_frameworks!
 pod "SnapSliderFilters"
 end

Regards,
Hary

**Comment by NeoTime** [comment]
Hi Hary,

I'm working with a tutorial on Nooma.tv - ZappyCoders try their tutorials there.  Thanks for reaching out.

Jeff
